apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-data-pv
  labels:
    type: local
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/data"
