from typing import Protocol


class SupportsRichComparison[T](Protocol[T]):
    def __lt__(self, other: T) -> bool: ...
    def __le__(self, other: T) -> bool: ...
    def __gt__(self, other: T) -> bool: ...
    def __ge__(self, other: T) -> bool: ...
    def __eq__(self, other: T) -> bool: ...
    def __ne__(self, other: T) -> bool: ...
