apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: apply2jobs-api:latest
          env:
            - name: MONGODB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongo-initdb
                  key: username
            - name: MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-initdb
                  key: password
            - name: LINKEDIN_USERNAME
              valueFrom:
                secretKeyRef:
                  name: linkedin-credentials
                  key: username
            - name: LINKEDIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: linkedin-credentials
                  key: password
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
          ports:
            - containerPort: 8000
